### PR TITLE
Mainly fix A_mul_B! for general Toeplitz

### LINKED ISSUE #27: error with inplace definition
Hi,

I think there is a mistake [here](https://github.com/JuliaMatrices/ToeplitzMatrices.jl/blob/master/src/ToeplitzMatrices.jl#L96)

Best regards

### PR DESCRIPTION
**Pull request by andreasnoack**
Fixes #27

...but also update to test on 0.6 and use testsets.

### CODE REVIEW

**Comment by andreasnoack** [comment]
@dlfivefifty Could you take a look at the test failure? Has something changed in `FastTransforms`?

**Comment by dlfivefifty** [comment]
I'll look att hat now

**Comment by dlfivefifty** [comment]
OK, I found an issue, but it looks different than what's failing the test. The issue is thagt
```julia
similar(x,TS,size(A,1)) # matmul.jl line 79
```
creates an array of `BigFloat` with unallocated entries. Then the line
```julia
yi   = ifelse(iszero(β), zero(β), y[i]*β) # ToeplitzMatrices.jl line 85
```
multiplies the unallocated entry by zero.

**Comment by andreasnoack** [comment]
Hm, right. I didn't consider that the elements could be uninitialized. I'll push a fix for that. However, I still see the `FastTransforms` issue locally.

**Comment by dlfivefifty** [comment]
As far as I can tell this is a Julia type inference bug: why would `T1` and `T2` be any in the following:
```julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-apple-darwin16.7.0

julia> function myToeplitz(vc::Vector, vr::Vector)
           m, n = length(vc), length(vr)
           T1 = eltype(vc)
           T2 = eltype(vr)
           T = promote_type(T1, T2, Float32)

           "hi"
       end
myToeplitz (generic function with 1 method)

julia> vc,vr = (BigFloat[1,2,3,4,5], BigFloat[1,6,7,8,0])
(BigFloat[1.000000000000000000000000000000000000000000000000000000000000000000000000000000, 2.000000000000000000000000000000000000000000000000000000000000000000000000000000, 3.000000000000000000000000000000000000000000000000000000000000000000000000000000, 4.000000000000000000000000000000000000000000000000000000000000000000000000000000, 5.000000000000000000000000000000000000000000000000000000000000000000000000000000], BigFloat[1.000000000000000000000000000000000000000000000000000000000000000000000000000000, 6.000000000000000000000000000000000000000000000000000000000000000000000000000000, 7.000000000000000000000000000000000000000000000000000000000000000000000000000000, 8.000000000000000000000000000000000000000000000000000000000000000000000000000000, 0.000000000000000000000000000000000000000000000000000000000000000000000000000000])

julia> @code_warntype myToeplitz(vc,vr)
Variables:
  #self#::#myToeplitz
  vc::Array{BigFloat,1}
  vr::Array{BigFloat,1}
  m::Int64
  n::Int64
  T1::Any
  T2::Any
  T::Any

Body:
  begin 
      (Base.arraylen)(vc::Array{BigFloat,1})::Int64
      (Base.arraylen)(vr::Array{BigFloat,1})::Int64 # line 7:
      return "hi"
  end::String
```

**Comment by andreasnoack** [comment]
I think it is because they aren't used so type inference just saves the work since they are elided later anyway. If `T`, `T1`, `T2` are returned, they are inferred.

**Comment by dlfivefifty** [comment]
OK, here's a better example of the bug:
```julia
julia> function myToeplitz(vc::Vector, vr::Vector)
           m, n = length(vc), length(vr)
           if vc[1] != vr[1]
               error("First element of the vectors must be the same")
           end

           T1 = eltype(vc)
           T2 = eltype(vr)

           T = promote_type(T1, T2, Float32)
           vcp, vrp = Vector{T}(vc), Vector{T}(vr)

           tmp = Vector{promote_type(T, Complex{Float32})}(m + n - 1)

           vcp, vrp, tmp
       end
myToeplitz (generic function with 1 method)

julia> @code_warntype myToeplitz(BigFloat[1,2,3,4,5], BigFloat[1,6,7,8,0])
Variables:
  #self#::#myToeplitz
  vc::Array{BigFloat,1}
  vr::Array{BigFloat,1}
  m::Int64
  n::Int64
  T1::Any
  T2::Any
  T::Any
  vcp::Any
  vrp::Any
  tmp::Array{Complex{BigFloat},1}

Body:
  begin 
      NewvarNode(:(tmp::Array{Complex{BigFloat},1}))
      SSAValue(0) = (Base.arraylen)(vc::Array{BigFloat,1})::Int64
      SSAValue(1) = (Base.arraylen)(vr::Array{BigFloat,1})::Int64 # line 3:
      SSAValue(5) = (Base.arrayref)(vc::Array{BigFloat,1}, 1)::BigFloat
      SSAValue(4) = (Base.arrayref)(vr::Array{BigFloat,1}, 1)::BigFloat
      $(Expr(:inbounds, false))
      # meta: location operators.jl != 129
      # meta: location mpfr.jl == 667
      SSAValue(8) = $(Expr(:foreigncall, (:mpfr_equal_p, :libmpfr), Int32, svec(Ptr{BigFloat}, Ptr{BigFloat}), :(&SSAValue(5)), SSAValue(5), :(&SSAValue(4)), SSAValue(4)))
      # meta: pop location
      # meta: pop location
      $(Expr(:inbounds, :pop))
      unless (Base.not_int)((Base.not_int)(((Base.sext_int)(Int64, SSAValue(8))::Int64 === 0)::Bool)::Bool)::Bool goto 17 # line 4:
      (Base.throw)($(Expr(:new, :(Core.ErrorException), "First element of the vectors must be the same")))::Union{}
      17:  # line 13:
      tmp::Array{Complex{BigFloat},1} = $(Expr(:foreigncall, :(:jl_alloc_array_1d), Array{Complex{BigFloat},1}, svec(Any, Int64), Array{Complex{BigFloat},1}, 0, :((Base.sub_int)((Base.add_int)(SSAValue(0), SSAValue(1))::Int64, 1)::Int64), 0)) # line 15:
      return (Core.tuple)(vc::Array{BigFloat,1}, vr::Array{BigFloat,1}, tmp::Array{Complex{BigFloat},1})::Tuple{Array{BigFloat,1},Array{BigFloat,1},Array{Complex{BigFloat},1}}
  end::Tuple{Array{BigFloat,1},Array{BigFloat,1},Array{Complex{BigFloat},1}}
```

**Comment by dlfivefifty** [comment]
Hmm, nevermind, `tmp` is inferred correctly. 

It looks like the issue is that the code `Toeplitz(BigFloat[1,2,3,4,5], BigFloat[1,6,7,8,0])` is compiled _before_ the call to `using FastTransforms`. I have no idea why that should be the case, but changing to the following resolves it:
```julia
if isdir(Pkg.dir("FastTransforms"))
    using FastTransforms
end
if isdir(Pkg.dir("FastTransforms"))
    @testset "BigFloat" begin
        T = Toeplitz(BigFloat[1,2,3,4,5], BigFloat[1,6,7,8,0])
        @test T*ones(BigFloat,5) ≈ [22,24,19,16,15]

        n = 512
        r = map(BigFloat,rand(n))
        T = Toeplitz(r,[r[1];map(BigFloat,rand(n-1))])
        @test T*ones(BigFloat,n) ≈ full(T)*ones(BigFloat,n)

        T = TriangularToeplitz(BigFloat[1,2,3,4,5],:L)
        @test T*ones(BigFloat,5) ≈ full(T)*ones(BigFloat,5)

        n = 512
        r = map(BigFloat,rand(n))
        T = TriangularToeplitz(r,:L)
        @test T*ones(BigFloat,n) ≈ full(T)*ones(BigFloat,n)

        T = TriangularToeplitz(BigFloat[1,2,3,4,5],:U)
        @test T*ones(BigFloat,5) ≈ full(T)*ones(BigFloat,5)

        n = 512
        r = map(BigFloat,rand(n))
        T = TriangularToeplitz(r,:U)
        @test T*ones(BigFloat,n) ≈ full(T)*ones(BigFloat,n)
    end
end
```

**Comment by andreasnoack** [comment]
Hm, weird. Thanks for identifying the issue.

**Comment by andreasnoack** [comment]
Things are working now. @dlfivefifty Would you have a problem with dropping 0.5 support?

**Comment by dlfivefifty** [comment]
No problem, in fact I'd encourage it (so that it's possible to start adding 0.7 compatibility with using the `where` syntax).

**Comment by andreasnoack** [comment]
I've allowed failure on master because some of the dependencies are not ready for master, e.g. `LowRankApprox`. We should reenable when we are closer to 0.7.

**Comment by dlfivefifty** [comment]
👍 0.7 has a number of bugs (just came across one in `@evalpoly` breaking FastGaussQuadrature.jl) that makes it unrealistic to support

**Pull request merged**
