### PR TITLE
Add more convert methods

### PR DESCRIPTION
**Pull request by dlfivefifty**
This supports, for example,

Matrix(Toeplitz([1.,1.],[1.,1.]))

Also adds support for Char inputs to create TriangularToeplitz

### CODE REVIEW

**Comment by andreasnoack** [comment]
Thanks. Looks great. Only thing is that I'd like to avoid is the constructor with the `Char` argument and only expose the `Symbol` version. That is the default in Base and I think it is better to only have a single version.

**Comment by dlfivefifty** [comment]
Ok no worries I'll update it

**Comment by dlfivefifty** [comment]
This has now been changed.

**Comment by andreasnoack** [comment]
Great. Thanks.

**Pull request merged**
