### PR TITLE
Package maintenance

### LINKED ISSUE #23: Define A_mul_B! instead of * for Hankel
Then `Base.LinAlg.:*` should do the necessary work and we have fast in-place multiplication with `Hankel` matrices. This is e.g. a problem if you pass in a `Hankel` to `eigs` because it is based on `A_mul_B!` which will then call the fallback `n^2` matvec.

### LINKED ISSUE #30: T*T is broken when T is triangular
```julia
julia> using ToeplitzMatrices

julia> n=600; c=2.0
2.0

julia> T=TriangularToeplitz([1;-c;zeros(n-2)],:U);

julia> T*T
ERROR: MethodError: no method matching ToeplitzMatrices.TriangularToeplitz(::Array{Float64,1}, ::Char)
Closest candidates are:
  ToeplitzMatrices.TriangularToeplitz(::Array{T<:Number,1}, ::Char, ::Array{S<:Number,1}, ::Array{S<:Number,1}, ::Base.DFT.Plan) where {T<:Number, S<:Number} at /Users/solver/.julia/v0.6/ToeplitzMatrices/src/ToeplitzMatrices.jl:354
  ToeplitzMatrices.TriangularToeplitz(::Array{T,1} where T, ::Symbol) at /Users/solver/.julia/v0.6/ToeplitzMatrices/src/ToeplitzMatrices.jl:362
Stacktrace:
 [1] *(::ToeplitzMatrices.TriangularToeplitz{Float64,Complex{Float64}}, ::ToeplitzMatrices.TriangularToeplitz{Float64,Complex{Float64}}) at /Users/solver/.julia/v0.6/ToeplitzMatrices/src/ToeplitzMatrices.jl:418
```

### PR DESCRIPTION
**Pull request by dkarrasch**
Sorry @andreasnoack, you merged too quickly. 😄 

I found that the branching version is significantly faster than the one using `mod`. For instance, `Matrix(C)` for a 100x100 circulant matrix takes 82µs with `mod` vs. 15µs with the branching. The single indexing method should be obsolete since this is handled by Base. If we want to leave it anyway, then we should perhaps compute a single `j, i = divrem(i - 1, size(A, 1)); return A[i+1, j+1]`.

Closes #23. And closes #30.

### CODE REVIEW

**Comment by dkarrasch** [comment]
It also speeds up small circulant matrix-vector multiplication:
```julia
juli> using ToeplitzMatrices, BenchmarkTools

julia> C = Circulant(rand(250));

julia> x = rand(250);

julia> @btime $C*$x;
  57.374 μs (1 allocation: 2.06 KiB) # PR
  451.078 μs (1 allocation: 2.06 KiB) # current
```

**Comment by dkarrasch** [comment]
There's some more to come, so please hold the line...

**Comment by dkarrasch** [comment]
I ran Aqua.jl and fixed a couple of ambiguity issues. Among these were the wrong usage of `Adjoint` types, so I fixed multiplication of `Circulant`s and their adjoints, and added some tests. While I was at it, I also added `mul!` methods for Hankel, which yields a significant speed-up in terms of performance, at the expense of more allocations:

```julia
julia> using Arpack, ToeplitzMatrices

julia> H = Hankel(rand(250, 250));

julia> using BenchmarkTools

julia> @btime eigs($H);
  15.823 ms (766 allocations: 91.70 KiB) # PR
  28.141 ms (670 allocations: 88.20 KiB) # latest release

julia> H = Hankel(rand(500, 500));

julia> using FFTW

julia> @btime eigs($H);
  55.917 ms (7811 allocations: 5.39 MiB) # PR
  166.441 ms (953 allocations: 157.03 KiB) # latest release
```
Perhaps the view with the negative stride should be materialized? I'll experiment with it some further.

**Comment by dkarrasch** [comment]
Ok, it feels like (almost) every untested function was in a broken state. 🤣 By now, only a couple of dimension mismatch lines are uncovered. So this is ready for review and merging.

**Comment by dlfivefifty** [comment]
This package was sorely in need of some love.. thanks so much!

**Comment by dkarrasch** [comment]
Gentle bump. I guess having excellent coverage will be good for the other open PRs.

**Review by andreasnoack — APPROVED** [review]
Thanks for the maintenance here

**Pull request merged**
