### PR TITLE
Add `ToeplitzFactorization`

### PR DESCRIPTION
**Pull request by devmotion**
This PR fixes https://github.com/JuliaMatrices/ToeplitzMatrices.jl/issues/36 and adds a `ToeplitzFactorization` object that can be created with `factorize(::AbstractToeplitz)`. If it is not provided explicitly, it will be created implicitly for computations that are based on the FFT.

Additionally, the PR fixes https://github.com/JuliaMatrices/ToeplitzMatrices.jl/issues/57 and fixes https://github.com/JuliaMatrices/ToeplitzMatrices.jl/issues/44.

### CODE REVIEW

**Comment by dlfivefifty** [comment]
Awesome! 

@andreasnoack will this break your usage of the package? It means you would have to call `factorize`.

It might be better to have `ToeplitzFactorization <: AbstractMatrix` instead of `<: Factorization` so that `factorize(Toeplitz(...))` maintains the current functionality of `Toeplitz(...)`. I don't see any drawback in this.

**Comment by dlfivefifty** [comment]
Down the line we should template out the vector type, e.g. I'd like to be able to represent infinite Toeplitz operators using this, but I can make that change later.

**Comment by devmotion** [comment]
> Down the line we should template out the vector type, e.g. I'd like to be able to represent infinite Toeplitz operators using this, but I can make that change later.

I noticed different things that could be improved but I tried to focus on the factorization only.

So far, `ToeplitzFactorization <: Factorization` only supports a subset of the methods of `AbstractToeplitz` and in particular does not carry around `vr` and `vc` (since also not all matrix types specify both) or the original matrix. Do you suggest that `ToeplitzFactorization` supports a superset of the methods of `AbstractToeplitz`? If it is not actually a `Factorization` instance anymore, maybe one should also use a different name?

**Comment by dlfivefifty** [comment]
> If it is not actually a Factorization instance anymore, maybe one should also use a different name?

Note its fine for `factorize` to return an `AbstractMatrix`:
```julia
julia> factorize(UpperTriangular(randn(5,5)))
5×5 UpperTriangular{Float64, Matrix{Float64}}:
 -0.483984   1.55636   0.736793  0.516085  -1.35191
   ⋅        -0.73876  -1.14913   0.208017  -1.68431
   ⋅          ⋅        0.050477  0.200336  -0.680405
   ⋅          ⋅         ⋅        0.168884   0.209434
   ⋅          ⋅         ⋅         ⋅        -0.0386784
```
Whether it's called `ToeplitzFactorization` is another question.

Though let's see if anyone cares, otherwise we can leave it `<: Factorization` since personally I don't care

**Comment by dlfivefifty** [comment]
As no one has raised a concern, I think the best thing to do is merge and tag and see if anyone complains.

Please bump the minor version in Project.toml and let me know when you are happy and I'll merge and tag.

**Comment by devmotion** [comment]
I updated the README and the version number, I guess it's fine now.

**Pull request merged**
