### PR TITLE
Add support for Julia 0.6

### PR DESCRIPTION
**Pull request by dlfivefifty**
Also, drops support for Julia 0.4

### CODE REVIEW

**Comment by andreasnoack** [comment]
I'm wondering what is happening on 0.5. Have you tried to run the tests on 0.5 locally?

**Comment by dlfivefifty** [comment]
Yes they passed

**Comment by andreasnoack** [comment]
Try to run them with `julia --check-bounds=yes -e 'Pkg.test("ToeplitzMatrices"; coverage=true)'`. I can reproduce it with that command.

**Comment by andreasnoack** [comment]
I've pushed a small change that disables a single test on 0.5 on Travis because inlining is turned off and therefore the test is too slow to finish in time.

**Pull request merged**
